version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    env_file: .env
    depends_on:
      - backend

  web_app:
    build:
      context: .
      dockerfile: docker/web_app.Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: beit_almahashi
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: